// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ahleongzc/leetcode-live-backend/cmd/app"
)

// Injectors from wire.go:

func InitializeApplication() (*app.Application, error) {
	application := app.NewApplication()
	return application, nil
}
