// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ahleongzc/leetcode-live-backend/cmd/app"
	"github.com/ahleongzc/leetcode-live-backend/internal/background"
	"github.com/ahleongzc/leetcode-live-backend/internal/config"
	"github.com/ahleongzc/leetcode-live-backend/internal/handler"
	"github.com/ahleongzc/leetcode-live-backend/internal/infra"
	"github.com/ahleongzc/leetcode-live-backend/internal/middleware"
	"github.com/ahleongzc/leetcode-live-backend/internal/repo"
	"github.com/ahleongzc/leetcode-live-backend/internal/scenario"
	"github.com/ahleongzc/leetcode-live-backend/internal/service"
)

// Injectors from wire.go:

func InitializeApplication() (*app.Application, error) {
	databaseConfig, err := config.LoadDatabaseConfig()
	if err != nil {
		return nil, err
	}
	db, err := infra.NewPostgresDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepo := repo.NewUserRepo(db)
	sessionRepo := repo.NewSessionRepo(db)
	authScenario := scenario.NewAuthScenario(userRepo, sessionRepo)
	authService := service.NewAuthService(authScenario, sessionRepo, userRepo)
	authHandler := handler.NewAuthHandler(authService)
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService)
	reviewRepo := repo.NewReviewRepo(db)
	interviewRepo := repo.NewInterviewRepo(db)
	transcriptRepo := repo.NewTranscriptRepo(db)
	transcriptManager := scenario.NewTranscriptManager(transcriptRepo)
	llmConfig, err := config.LoadLLMConfig()
	if err != nil {
		return nil, err
	}
	client := infra.NewHTTPCLient()
	llm, err := infra.NewLLM(llmConfig, client)
	if err != nil {
		return nil, err
	}
	reviewScenario := scenario.NewReviewScenario(reviewRepo, interviewRepo, transcriptManager, llm)
	healthHandler := handler.NewHealthHandler(reviewScenario)
	websocketConfig := config.LoadWebsocketConfig()
	questionRepo := repo.NewQuestionRepo(db)
	objectStorageConfig, err := config.LoadObjectStorageConfig()
	if err != nil {
		return nil, err
	}
	s3Client, err := infra.NewCloudflareR2ObjectStorageClient(objectStorageConfig)
	if err != nil {
		return nil, err
	}
	fileRepo := repo.NewFileRepo(s3Client, objectStorageConfig)
	ttsConfig, err := config.LoadTTSConfig()
	if err != nil {
		return nil, err
	}
	tts, err := infra.NewTTS(ttsConfig, client)
	if err != nil {
		return nil, err
	}
	interviewScenario := scenario.NewInterviewScenario(transcriptManager, questionRepo, interviewRepo, fileRepo, llm, tts)
	questionScenario := scenario.NewQuestionScenario(questionRepo)
	intentClassifier := scenario.NewIntentClassifier()
	interviewService := service.NewInterviewService(interviewScenario, authScenario, questionScenario, intentClassifier, interviewRepo, transcriptManager)
	logger := infra.NewZerologLogger()
	interviewHandler := handler.NewInterviewHandler(websocketConfig, authService, interviewService, logger)
	middlewareMiddleware := middleware.NewMiddleware(logger)
	houseKeeper := background.NewHouseKeeper(sessionRepo, logger)
	application := app.NewApplication(authHandler, userHandler, healthHandler, interviewHandler, middlewareMiddleware, houseKeeper)
	return application, nil
}
