// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/ahleongzc/leetcode-live-backend/cmd/app"
	"github.com/ahleongzc/leetcode-live-backend/internal/config"
	"github.com/ahleongzc/leetcode-live-backend/internal/handler"
	"github.com/ahleongzc/leetcode-live-backend/internal/infra"
	"github.com/ahleongzc/leetcode-live-backend/internal/middleware"
	"github.com/ahleongzc/leetcode-live-backend/internal/repo"
	"github.com/ahleongzc/leetcode-live-backend/internal/service"
)

// Injectors from wire.go:

func InitializeApplication() (*app.Application, error) {
	databaseConfig := config.LoadDatabaseConfig()
	db, err := infra.NewPostgresDatabase(databaseConfig)
	if err != nil {
		return nil, err
	}
	sessionRepo := repo.NewSessionRepo(db)
	authService := service.NewAuthService(sessionRepo)
	authHandler := handler.NewAuthHandler(authService)
	healthHandler := handler.NewHealthHandler()
	websocketConfig := config.LoadWebsocketConfig()
	interviewHandler := handler.NewInterviewHandler(websocketConfig, authService)
	logger := infra.NewZerologLogger()
	middlewareMiddleware := middleware.NewMiddleware(logger)
	application := app.NewApplication(authHandler, healthHandler, interviewHandler, middlewareMiddleware)
	return application, nil
}
