// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/interview_proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interview     *Interview             `protobuf:"bytes,1,opt,name=interview,proto3" json:"interview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_proto_interview_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_interview_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationResponse) GetInterview() *Interview {
	if x != nil {
		return x.Interview
	}
	return nil
}

type VerifyCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCandidateRequest) Reset() {
	*x = VerifyCandidateRequest{}
	mi := &file_proto_interview_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCandidateRequest) ProtoMessage() {}

func (x *VerifyCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCandidateRequest.ProtoReflect.Descriptor instead.
func (*VerifyCandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_interview_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyCandidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Interview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interview) Reset() {
	*x = Interview{}
	mi := &file_proto_interview_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interview) ProtoMessage() {}

func (x *Interview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interview_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interview.ProtoReflect.Descriptor instead.
func (*Interview) Descriptor() ([]byte, []int) {
	return file_proto_interview_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *Interview) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_interview_proxy_proto protoreflect.FileDescriptor

const file_proto_interview_proxy_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/interview_proxy.proto\"@\n" +
	"\x14VerificationResponse\x12(\n" +
	"\tinterview\x18\x01 \x01(\v2\n" +
	".InterviewR\tinterview\".\n" +
	"\x16VerifyCandidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x1b\n" +
	"\tInterview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2U\n" +
	"\x0eInterviewProxy\x12C\n" +
	"\x0fVerifyCandidate\x12\x17.VerifyCandidateRequest\x1a\x15.VerificationResponse\"\x00B8Z6github.com/ahleongzc/leetcode-live-backend/proto;protob\x06proto3"

var (
	file_proto_interview_proxy_proto_rawDescOnce sync.Once
	file_proto_interview_proxy_proto_rawDescData []byte
)

func file_proto_interview_proxy_proto_rawDescGZIP() []byte {
	file_proto_interview_proxy_proto_rawDescOnce.Do(func() {
		file_proto_interview_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interview_proxy_proto_rawDesc), len(file_proto_interview_proxy_proto_rawDesc)))
	})
	return file_proto_interview_proxy_proto_rawDescData
}

var file_proto_interview_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_interview_proxy_proto_goTypes = []any{
	(*VerificationResponse)(nil),   // 0: VerificationResponse
	(*VerifyCandidateRequest)(nil), // 1: VerifyCandidateRequest
	(*Interview)(nil),              // 2: Interview
}
var file_proto_interview_proxy_proto_depIdxs = []int32{
	2, // 0: VerificationResponse.interview:type_name -> Interview
	1, // 1: InterviewProxy.VerifyCandidate:input_type -> VerifyCandidateRequest
	0, // 2: InterviewProxy.VerifyCandidate:output_type -> VerificationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_interview_proxy_proto_init() }
func file_proto_interview_proxy_proto_init() {
	if File_proto_interview_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interview_proxy_proto_rawDesc), len(file_proto_interview_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interview_proxy_proto_goTypes,
		DependencyIndexes: file_proto_interview_proxy_proto_depIdxs,
		MessageInfos:      file_proto_interview_proxy_proto_msgTypes,
	}.Build()
	File_proto_interview_proxy_proto = out.File
	file_proto_interview_proxy_proto_goTypes = nil
	file_proto_interview_proxy_proto_depIdxs = nil
}
