// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/interview_proxy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterviewProxy_StartInterview_FullMethodName = "/InterviewProxy/StartInterview"
)

// InterviewProxyClient is the client API for InterviewProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterviewProxyClient interface {
	StartInterview(ctx context.Context, in *StartInterviewRequest, opts ...grpc.CallOption) (*StartInterviewResponse, error)
}

type interviewProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewInterviewProxyClient(cc grpc.ClientConnInterface) InterviewProxyClient {
	return &interviewProxyClient{cc}
}

func (c *interviewProxyClient) StartInterview(ctx context.Context, in *StartInterviewRequest, opts ...grpc.CallOption) (*StartInterviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInterviewResponse)
	err := c.cc.Invoke(ctx, InterviewProxy_StartInterview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterviewProxyServer is the server API for InterviewProxy service.
// All implementations must embed UnimplementedInterviewProxyServer
// for forward compatibility.
type InterviewProxyServer interface {
	StartInterview(context.Context, *StartInterviewRequest) (*StartInterviewResponse, error)
	mustEmbedUnimplementedInterviewProxyServer()
}

// UnimplementedInterviewProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterviewProxyServer struct{}

func (UnimplementedInterviewProxyServer) StartInterview(context.Context, *StartInterviewRequest) (*StartInterviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInterview not implemented")
}
func (UnimplementedInterviewProxyServer) mustEmbedUnimplementedInterviewProxyServer() {}
func (UnimplementedInterviewProxyServer) testEmbeddedByValue()                        {}

// UnsafeInterviewProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterviewProxyServer will
// result in compilation errors.
type UnsafeInterviewProxyServer interface {
	mustEmbedUnimplementedInterviewProxyServer()
}

func RegisterInterviewProxyServer(s grpc.ServiceRegistrar, srv InterviewProxyServer) {
	// If the following call pancis, it indicates UnimplementedInterviewProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterviewProxy_ServiceDesc, srv)
}

func _InterviewProxy_StartInterview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInterviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewProxyServer).StartInterview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterviewProxy_StartInterview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewProxyServer).StartInterview(ctx, req.(*StartInterviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterviewProxy_ServiceDesc is the grpc.ServiceDesc for InterviewProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterviewProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InterviewProxy",
	HandlerType: (*InterviewProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartInterview",
			Handler:    _InterviewProxy_StartInterview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interview_proxy.proto",
}
