// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/interview_proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Source int32

const (
	Source_UNKNOWN Source = 0
	Source_CLIENT  Source = 1
	Source_SERVER  Source = 2
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0: "UNKNOWN",
		1: "CLIENT",
		2: "SERVER",
	}
	Source_value = map[string]int32{
		"UNKNOWN": 0,
		"CLIENT":  1,
		"SERVER":  2,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_interview_proxy_proto_enumTypes[0].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_pb_interview_proxy_proto_enumTypes[0]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{0}
}

type InterviewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        Source                 `protobuf:"varint,1,opt,name=source,proto3,enum=Source" json:"source,omitempty"`
	InterviewId   uint64                 `protobuf:"varint,2,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	Chunk         *string                `protobuf:"bytes,3,opt,name=chunk,proto3,oneof" json:"chunk,omitempty"`
	Code          *string                `protobuf:"bytes,4,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Url           *string                `protobuf:"bytes,5,opt,name=url,proto3,oneof" json:"url,omitempty"`
	End           bool                   `protobuf:"varint,6,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterviewMessage) Reset() {
	*x = InterviewMessage{}
	mi := &file_pb_interview_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterviewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterviewMessage) ProtoMessage() {}

func (x *InterviewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterviewMessage.ProtoReflect.Descriptor instead.
func (*InterviewMessage) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *InterviewMessage) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_UNKNOWN
}

func (x *InterviewMessage) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

func (x *InterviewMessage) GetChunk() string {
	if x != nil && x.Chunk != nil {
		return *x.Chunk
	}
	return ""
}

func (x *InterviewMessage) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *InterviewMessage) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *InterviewMessage) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

type VerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   *uint64                `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3,oneof" json:"interview_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_pb_interview_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationResponse) GetInterviewId() uint64 {
	if x != nil && x.InterviewId != nil {
		return *x.InterviewId
	}
	return 0
}

type VerifyCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCandidateRequest) Reset() {
	*x = VerifyCandidateRequest{}
	mi := &file_pb_interview_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCandidateRequest) ProtoMessage() {}

func (x *VerifyCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCandidateRequest.ProtoReflect.Descriptor instead.
func (*VerifyCandidateRequest) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCandidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinInterviewRequest) Reset() {
	*x = JoinInterviewRequest{}
	mi := &file_pb_interview_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinInterviewRequest) ProtoMessage() {}

func (x *JoinInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinInterviewRequest.ProtoReflect.Descriptor instead.
func (*JoinInterviewRequest) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *JoinInterviewRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

type JoinInterviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinInterviewResponse) Reset() {
	*x = JoinInterviewResponse{}
	mi := &file_pb_interview_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinInterviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinInterviewResponse) ProtoMessage() {}

func (x *JoinInterviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinInterviewResponse.ProtoReflect.Descriptor instead.
func (*JoinInterviewResponse) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{4}
}

type PauseInterviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterviewId   uint64                 `protobuf:"varint,1,opt,name=interview_id,json=interviewId,proto3" json:"interview_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseInterviewRequest) Reset() {
	*x = PauseInterviewRequest{}
	mi := &file_pb_interview_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseInterviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseInterviewRequest) ProtoMessage() {}

func (x *PauseInterviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseInterviewRequest.ProtoReflect.Descriptor instead.
func (*PauseInterviewRequest) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *PauseInterviewRequest) GetInterviewId() uint64 {
	if x != nil {
		return x.InterviewId
	}
	return 0
}

type PauseInterviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseInterviewResponse) Reset() {
	*x = PauseInterviewResponse{}
	mi := &file_pb_interview_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseInterviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseInterviewResponse) ProtoMessage() {}

func (x *PauseInterviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interview_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseInterviewResponse.ProtoReflect.Descriptor instead.
func (*PauseInterviewResponse) Descriptor() ([]byte, []int) {
	return file_pb_interview_proxy_proto_rawDescGZIP(), []int{6}
}

var File_pb_interview_proxy_proto protoreflect.FileDescriptor

const file_pb_interview_proxy_proto_rawDesc = "" +
	"\n" +
	"\x18pb/interview_proxy.proto\"\xce\x01\n" +
	"\x10InterviewMessage\x12\x1f\n" +
	"\x06source\x18\x01 \x01(\x0e2\a.SourceR\x06source\x12!\n" +
	"\finterview_id\x18\x02 \x01(\x04R\vinterviewId\x12\x19\n" +
	"\x05chunk\x18\x03 \x01(\tH\x00R\x05chunk\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x04 \x01(\tH\x01R\x04code\x88\x01\x01\x12\x15\n" +
	"\x03url\x18\x05 \x01(\tH\x02R\x03url\x88\x01\x01\x12\x10\n" +
	"\x03end\x18\x06 \x01(\bR\x03endB\b\n" +
	"\x06_chunkB\a\n" +
	"\x05_codeB\x06\n" +
	"\x04_url\"O\n" +
	"\x14VerificationResponse\x12&\n" +
	"\finterview_id\x18\x01 \x01(\x04H\x00R\vinterviewId\x88\x01\x01B\x0f\n" +
	"\r_interview_id\".\n" +
	"\x16VerifyCandidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"9\n" +
	"\x14JoinInterviewRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\"\x17\n" +
	"\x15JoinInterviewResponse\":\n" +
	"\x15PauseInterviewRequest\x12!\n" +
	"\finterview_id\x18\x01 \x01(\x04R\vinterviewId\"\x18\n" +
	"\x16PauseInterviewResponse*-\n" +
	"\x06Source\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x022\x9a\x02\n" +
	"\x0eInterviewProxy\x12A\n" +
	"\x0fVerifyCandidate\x12\x17.VerifyCandidateRequest\x1a\x15.VerificationResponse\x12>\n" +
	"\rJoinInterview\x12\x15.JoinInterviewRequest\x1a\x16.JoinInterviewResponse\x12A\n" +
	"\x0ePauseInterview\x12\x16.PauseInterviewRequest\x1a\x17.PauseInterviewResponse\x12B\n" +
	"\x16ProcessIncomingMessage\x12\x11.InterviewMessage\x1a\x11.InterviewMessage(\x010\x01B2Z0github.com/ahleongzc/leetcode-live-backend/pb;pbb\x06proto3"

var (
	file_pb_interview_proxy_proto_rawDescOnce sync.Once
	file_pb_interview_proxy_proto_rawDescData []byte
)

func file_pb_interview_proxy_proto_rawDescGZIP() []byte {
	file_pb_interview_proxy_proto_rawDescOnce.Do(func() {
		file_pb_interview_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_interview_proxy_proto_rawDesc), len(file_pb_interview_proxy_proto_rawDesc)))
	})
	return file_pb_interview_proxy_proto_rawDescData
}

var file_pb_interview_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_interview_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_interview_proxy_proto_goTypes = []any{
	(Source)(0),                    // 0: Source
	(*InterviewMessage)(nil),       // 1: InterviewMessage
	(*VerificationResponse)(nil),   // 2: VerificationResponse
	(*VerifyCandidateRequest)(nil), // 3: VerifyCandidateRequest
	(*JoinInterviewRequest)(nil),   // 4: JoinInterviewRequest
	(*JoinInterviewResponse)(nil),  // 5: JoinInterviewResponse
	(*PauseInterviewRequest)(nil),  // 6: PauseInterviewRequest
	(*PauseInterviewResponse)(nil), // 7: PauseInterviewResponse
}
var file_pb_interview_proxy_proto_depIdxs = []int32{
	0, // 0: InterviewMessage.source:type_name -> Source
	3, // 1: InterviewProxy.VerifyCandidate:input_type -> VerifyCandidateRequest
	4, // 2: InterviewProxy.JoinInterview:input_type -> JoinInterviewRequest
	6, // 3: InterviewProxy.PauseInterview:input_type -> PauseInterviewRequest
	1, // 4: InterviewProxy.ProcessIncomingMessage:input_type -> InterviewMessage
	2, // 5: InterviewProxy.VerifyCandidate:output_type -> VerificationResponse
	5, // 6: InterviewProxy.JoinInterview:output_type -> JoinInterviewResponse
	7, // 7: InterviewProxy.PauseInterview:output_type -> PauseInterviewResponse
	1, // 8: InterviewProxy.ProcessIncomingMessage:output_type -> InterviewMessage
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_interview_proxy_proto_init() }
func file_pb_interview_proxy_proto_init() {
	if File_pb_interview_proxy_proto != nil {
		return
	}
	file_pb_interview_proxy_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_interview_proxy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_interview_proxy_proto_rawDesc), len(file_pb_interview_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_interview_proxy_proto_goTypes,
		DependencyIndexes: file_pb_interview_proxy_proto_depIdxs,
		EnumInfos:         file_pb_interview_proxy_proto_enumTypes,
		MessageInfos:      file_pb_interview_proxy_proto_msgTypes,
	}.Build()
	File_pb_interview_proxy_proto = out.File
	file_pb_interview_proxy_proto_goTypes = nil
	file_pb_interview_proxy_proto_depIdxs = nil
}
